spring.application.name=notesapp

spring.datasource.url=jdbc:mysql://localhost:3306/notesdb
spring.datasource.username=root
spring.datasource.password=746296

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
